services:
  postgres:
    image: postgres:17.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:9.5
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: carlos@viaresults.com.br
      PGADMIN_DEFAULT_PASSWORD: cbgomes
    ports:
      - 8083:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - local-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: rabbitmq-my-bank
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - local-network

volumes:
  postgres-data:
  pgadmin-data:
  rabbitmq_data:

networks:
  local-network:
    driver: bridge